### ISSUE TITLE
Examples don't work properly

### ISSUE THREAD

**Issue by Adewotta** [GRRLIB/GRRLIB#10]
I was unable to properly run a few of the examples in the newest version of GRRLIB. 
Bitmap_fx
3D_sample3
unlimited2D

I didn't test many more of them, None of these properly display textures or text for me, they end up corrupted or don't display at all, however using GRRLIB 4.3.2 seemed to fix the issue.

**Comment by Crayon2000** [comment]
Hello @Adewotta, I was able to run the examples you mentioned on my Wii U and on Dolphin without any problems. Currently my Wii is not available.

![image](https://user-images.githubusercontent.com/11451841/110079538-3b924300-7d57-11eb-9deb-ee48eaa3d7fb.png)

I am now creating an archive when doing the CI that contains all compiled examples. Can you download the examples and test them: https://github.com/GRRLIB/GRRLIB/suites/2184722066/artifacts/44993611
If it's working, your setup might be the problem.

**Comment by Adewotta** [comment]
They do appear to work for me, I am assuming I messed up my setup somehow, since it worked again after using the old version. Although how it could have compiled with an incomplete or broken setup is beyond me. I reinstalled the newest version and tried compiling again myself as well and it works.
