### ISSUE TITLE
problem compilng

### ISSUE THREAD

**Issue by Hunterrules0-0** [GRRLIB/GRRLIB#29]
Whenever I try to compile I get this
`powerpc-eabi-gcc: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files'`

**Comment by Crayon2000** [comment]
First, are you able to compile the template / examples from devkitppc?
If yes, second, are you able to install GRRLIB?
If yes, third, are you able to compile the template / examples from GRRLIB?

**Comment by Hunterrules0-0** [comment]
Im sorry I figured it out. I think. I just put it into another directory. Im sorry for wasting your time
