### ISSUE TITLE
GX_end is static compile warning

### ISSUE THREAD

**Issue by owensoft** [GRRLIB/GRRLIB#3]
Good day all.

just trying to update my libogc to the latest version but I am getting this warning when compiling my current project;

:/devkitPro/libogc/include/grrlib/GRRLIB_fbGX.h:45:5: warning: 'GX_End' is static but used in inline function 'GRRLIB_GXEngine' which is not static
     GX_End();
     ^~~~~~

I get about 17 or so errors anywhere a GX function ( e.g.  GX_Color1u32(color[i]); GX_Position3f32(v[i].x, v[i].y, v[i].z); )  is used in GRRLIB.  my own code compiles and runs fine.  is there anything I can do about the warnings or just ignore them?

**Comment by Crayon2000** [comment]
Hello @owensoft, are you using the code from the master branch or the 4.3.2 version released in 2015?

**Comment by owensoft** [comment]
yes, I just downloaded the master this morning and ran clean make.  the make runs without error.  then I recompiled my code in prog notepad on windows7 and got a the warnings.

**Comment by Crayon2000** [comment]
Try running `make clean all install`
Maybe you did not installed the library and you are using the old one.

If you look at this log from GRRMOD where GRRLIB version 4.3.2 is used you can see the same problem: https://travis-ci.org/GRRLIB/GRRMOD
But if you look at the GRRLIB where all the samples are built, there is no problem: https://travis-ci.org/GRRLIB/GRRLIB

I am pretty sure I fixed that problem in commit 3dbee76

**Comment by owensoft** [comment]
thanx I will recompile and test it again when I get home in a 6 hours.   will update with my findings when done.  thanx again

**Comment by owensoft** [comment]
Aw, issue resolved.  it was the classic case of not restarting after updating devkitpro.  worked fine after restarting and making GRRLIB again.  thanx
