### ISSUE TITLE
powerpc-eabi-gcc: No such file or directory

### ISSUE THREAD

**Issue by 404Dev-404** [GRRLIB/GRRLIB#30]
i cloned the grrlib source code and entered the directory GRRLIB and ran make clean but when i run make all i get this

`
-----------------------------------------------------------
-----------------------------------------------------------
pngu.c
make[2]: powerpc-eabi-gcc: No such file or directory
make[2]: *** [pngu.o] Error 1
make[1]: *** [all] Error 1
make: *** [all] Error 1
`

**Comment by Crayon2000** [comment]
It seems to be a problem with your toolchain. Can you compile other Wii homebrews?

If you need help with devkitPro you can look at https://devkitpro.org/wiki/Getting_Started

**Comment by 404Dev-404** [comment]
i can compile the wii examples template but i don't think that counts

**Comment by Crayon2000** [comment]
Are you on Linux, Windows or in a Docker container?

**Comment by 404Dev-404** [comment]
macos

**Comment by Crayon2000** [comment]
Can you paste the whole output when using `make clean all` in the *GRRLIB* folder, for example:
```bash
make[1]: Entering directory '/workspaces/GRRLIB/GRRLIB/GRRLIB'
rm -f GRRLIB_gecko.o GRRLIB_print.o GRRLIB_core.o GRRLIB_ttf.o GRRLIB_texEdit.o GRRLIB_fileIO.o GRRLIB_bmf.o GRRLIB_fbAdvanced.o GRRLIB_bmfx.o GRRLIB_render.o GRRLIB_3D.o GRRLIB_snapshot.o GRRLIB_gecko.d GRRLIB_print.d GRRLIB_core.d GRRLIB_ttf.d GRRLIB_texEdit.d GRRLIB_fileIO.d GRRLIB_bmf.d GRRLIB_fbAdvanced.d GRRLIB_bmfx.d GRRLIB_render.d GRRLIB_3D.d GRRLIB_snapshot.d libgrrlib.a
make[1]: Leaving directory '/workspaces/GRRLIB/GRRLIB/GRRLIB'
make[1]: Entering directory '/workspaces/GRRLIB/GRRLIB/lib'
make[2]: Entering directory '/workspaces/GRRLIB/GRRLIB/lib/pngu'
rm -f pngu.o pngu.d libpngu.a
make[2]: Leaving directory '/workspaces/GRRLIB/GRRLIB/lib/pngu'
make[1]: Leaving directory '/workspaces/GRRLIB/GRRLIB/lib'
-----------------------------------------------------------
make[1]: Entering directory '/workspaces/GRRLIB/GRRLIB/GRRLIB'
GRRLIB_gecko.c
GRRLIB_print.c
GRRLIB_core.c
GRRLIB_ttf.c
GRRLIB_texEdit.c
GRRLIB_fileIO.c
GRRLIB_bmf.c
GRRLIB_fbAdvanced.c
GRRLIB_bmfx.c
GRRLIB_render.c
GRRLIB_3D.c
GRRLIB_snapshot.c
powerpc-eabi-gcc-ar -r libgrrlib.a GRRLIB_gecko.o GRRLIB_print.o GRRLIB_core.o GRRLIB_ttf.o GRRLIB_texEdit.o GRRLIB_fileIO.o GRRLIB_bmf.o GRRLIB_fbAdvanced.o GRRLIB_bmfx.o GRRLIB_render.o GRRLIB_3D.o GRRLIB_snapshot.o
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ar: creating libgrrlib.a
make[1]: Leaving directory '/workspaces/GRRLIB/GRRLIB/GRRLIB'
-----------------------------------------------------------
make[1]: Entering directory '/workspaces/GRRLIB/GRRLIB/lib'
-----------------------------------------------------------
make[2]: Entering directory '/workspaces/GRRLIB/GRRLIB/lib/pngu'
pngu.c
powerpc-eabi-gcc-ar -r libpngu.a pngu.o
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ar: creating libpngu.a
make[2]: Leaving directory '/workspaces/GRRLIB/GRRLIB/lib/pngu'
make[1]: Leaving directory '/workspaces/GRRLIB/GRRLIB/lib'
```

**Comment by 404Dev-404** [comment]
` anthonyvaldes@aj  ~  cd Downloads/GRRLIB-4.4.1/
 anthonyvaldes@aj  ~/Downloads/GRRLIB-4.4.1  ls
CHANGELOG.md   LICENCE.md     docs           grrlib.doxygen
GRRLIB         README.md      examples
 anthonyvaldes@aj  ~/Downloads/GRRLIB-4.4.1  cd grrlib
 anthonyvaldes@aj  ~/Downloads/GRRLIB-4.4.1/grrlib  cd grrlib
 anthonyvaldes@aj  ~/Downloads/GRRLIB-4.4.1/grrlib/grrlib  ls
GRRLIB_3D.c         GRRLIB_fbAdvanced.c GRRLIB_render.c     Makefile
GRRLIB_bmf.c        GRRLIB_fileIO.c     GRRLIB_snapshot.c   grep
GRRLIB_bmfx.c       GRRLIB_gecko.c      GRRLIB_texEdit.c    grrlib
GRRLIB_core.c       GRRLIB_print.c      GRRLIB_ttf.c        grrlib.h
 anthonyvaldes@aj  ~/Downloads/GRRLIB-4.4.1/grrlib/grrlib  make clean all
rm -f GRRLIB_3D.o GRRLIB_bmf.o GRRLIB_bmfx.o GRRLIB_core.o GRRLIB_fbAdvanced.o GRRLIB_fileIO.o GRRLIB_gecko.o GRRLIB_print.o GRRLIB_render.o GRRLIB_snapshot.o GRRLIB_texEdit.o GRRLIB_ttf.o GRRLIB_3D.d GRRLIB_bmf.d GRRLIB_bmfx.d GRRLIB_core.d GRRLIB_fbAdvanced.d GRRLIB_fileIO.d GRRLIB_gecko.d GRRLIB_print.d GRRLIB_render.d GRRLIB_snapshot.d GRRLIB_texEdit.d GRRLIB_ttf.d libgrrlib.a
GRRLIB_3D.c
make: powerpc-eabi-gcc: No such file or directory
make: *** [GRRLIB_3D.o] Error 1
 ✘ anthonyvaldes@aj  ~/Downloads/GRRLIB-4.4.1/grrlib/grrlib `

**Comment by Crayon2000** [comment]
When you type `echo $DEVKITPPC` in your console where you are trying to compile, what do you get?

**Comment by 404Dev-404** [comment]
/opt/devkitpro/devkitPPC

**Comment by Crayon2000** [comment]
And when you type `/opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc --version`

**Comment by 404Dev-404** [comment]
powerpc-eabi-gcc (devkitPPC release 41) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Crayon2000** [comment]
Maybe you have an other version of the compiler! Can you simply try `powerpc-eabi-gcc --version`

**Comment by 404Dev-404** [comment]
zsh: command not found: powerpc-eabi-gcc

**Comment by Crayon2000** [comment]
The only thing I could think of is that you might have not done step 3:
1. To get the Xcode command line tools run `xcode-select --install` from Terminal.
2. Use the [pkg installer](https://github.com/devkitPro/pacman/releases/latest) to install [devkitPro pacman](https://devkitpro.org/wiki/devkitPro_pacman).
3. Reboot your mac to get environment set.
4. Use dkp-pacman to install your chosen tools as per Unix like platforms below.

Here is a post of someone having a similar problem: https://stackoverflow.com/questions/71047549/no-such-file-or-directory-arm-none-eabi-gcc-error-trying-to-make-micropython

**Comment by 404Dev-404** [comment]
i installed it a few days ago and i rebooted after

**Comment by 404Dev-404** [comment]
ill reboot again

**Comment by 404Dev-404** [comment]
i added export DEVKITPPC to my zshrc because i forgot but it still doesn't work

**Comment by 404Dev-404** [comment]
i added /opt/devkitpro/devkitPPC/bin to my path and now it compiles

**Comment by 404Dev-404** [comment]
forgot to make the last comment a close with comment comment so im closing it now
