### ISSUE TITLE
error with command make clean all install

### ISSUE THREAD

**Issue by Link-Games** [GRRLIB/GRRLIB#37]
when i am installing GRRLIB i dd all until the command make clean all install and it gives me the error:
C:\grr\GRRLIB>make clean all install
make: *** No rule to make target 'clean'.  Stop.
can someone help me?

**Comment by Crayon2000** [comment]
I'm not sure about your folder structure, but try to go in *C:\grr\GRRLIB\GRRLIB*
There are no *Makefile* in the root folder.

**Comment by Link-Games** [comment]
i installed grrlib in c:/grr
Thanks it works now.
