### ISSUE TITLE
GRRLIB_PrintfTTF and GRRLIB_PrintfTTFW do not display the text in correct alpha value

### ISSUE THREAD

**Issue by supertazon** [GRRLIB/GRRLIB#40]
Hi,

I would like to draw text with some transparency, however the text is always drawn fully opaque, no matter the A value in the RGBA color.
Example:
`GRRLIB_PrintfTTF(280, 180, GCFont,LG, fontSize, 0xFF000000);` or `GRRLIB_PrintfTTF(280, 180, GCFont,LG, fontSize, 0xFF000080);` will display the same thing as `GRRLIB_PrintfTTF(280, 180, GCFont,LG, fontSize, 0xFF0000FF);`

I'm not super knowledgeable in C but looking at the underlying GRRLIB code, it seems to me that the alpha component of the RGBA color is never passed down to the final DrawBitmap function. Instead it takes an argument that I don't really understand for the alpha value:
```C
static void DrawBitmap(FT_Bitmap *bitmap, int offset, int top, const u8 cR, const u8 cG, const u8 cB) {
    FT_Int i, j, p, q;
    FT_Int x_max = offset + bitmap->width;
    FT_Int y_max = top + bitmap->rows;

    for ( i = offset, p = 0; i < x_max; i++, p++ ) {
        for ( j = top, q = 0; j < y_max; j++, q++ ) {
            GX_Begin(GX_POINTS, GX_VTXFMT0, 1);
                GX_Position3f32(i, j, 0);
                GX_Color4u8(cR, cG, cB,
                            bitmap->buffer[ q * bitmap->width + p ]);
            GX_End();
        }
    }
}

**Comment by Crayon2000** [comment]
The alpha value on the `color` parameter is not used with `GRRLIB_PrintfTTF` because a TTF font as built-in alpha that needs to be rendered.

Check the _examples/basic_drawing/source/main.c_ sample code to see if the `GRRLIB_Printf` will work with what you need.

This code
```cpp
    GRRLIB_Printf(5, 25, tex_BMfont2, GRRLIB_WHITE, 1, "GRRLIB %s TEXT DEMO", GRRLIB_VER_STRING);

    GRRLIB_Printf(5, 100, tex_BMfont4, GRRLIB_WHITE, 1, "TO QUIT PRESS THE HOME BUTTON.");
    GRRLIB_Printf(5, 140, tex_BMfont4, GRRLIB_YELLOW, 1, "USE + OR - TO MOVE ACROSS PAGES.");
    GRRLIB_Printf(5, 180, tex_BMfont4, GRRLIB_GREEN, 1, "USE THE D-PAD TO MOVE STUFF.");
    GRRLIB_Printf(left, top+250, tex_BMfont1, GRRLIB_WHITE, 1, "IR X VALUE: %d", (int)ir1.x);
    GRRLIB_Printf(left, top+300, tex_BMfont3, GRRLIB_WHITE, 1, "IR Y VALUE: %d", (int)ir1.y);
    GRRLIB_Printf(left, top+350, tex_BMfont3, 0XFFFFFF50, 1, "TEXT WITH ALPHA");
    GRRLIB_Printf(left, top+400, tex_BMfont5, GRRLIB_LIME, 1, "This font has the 128 ASCII characters");
    GRRLIB_PrintBMF(left, top+420, bmf_Font2, "%s", bmf_Font2->name);
```

Will produce this:
![image](https://github.com/GRRLIB/GRRLIB/assets/11451841/f1cf9dad-b71e-4778-9d39-3cd56e091d4b)

If you really need `GRRLIB_PrintfTTF` you may try to print the text to a texture with `GRRLIB_Screen2Texture` and then try to apply alpha.

**Comment by Crayon2000** [comment]
If you don't need the full characters range of your TTF font and you will always use the same font size. You can try to generate a PNG from your font with a tool like [WiiBuilder](https://wiibrew.org/wiki/WiiBuilder).

These settings:
![image](https://github.com/GRRLIB/GRRLIB/assets/11451841/e1401824-76c7-409c-9026-272eeaa655de)

Will generate this file:
![OpenSymbol_18](https://github.com/GRRLIB/GRRLIB/assets/11451841/8ab41701-8f8e-479b-ad87-cbed714917b3)

This image can be easily used with `GRRLIB_Printf`.

**Comment by supertazon** [comment]
Thank you so much for clarifying, makes total sense. I can just suggest that on the documentation for these functions you could specify that the alpha value is not taken into account as it relies on the TTF’s core functioning.

I’ll look into either solutions you are suggesting. I am working on allowing users to customize the text on the GameCube intro animation for the Wii that I built thanks to GRRLIB (thanks so much for supporting the Lib after so many years!). I am using the Gamecuben font from Dafont and will test if rendering as a PNG would provide the same level of quality.

Do you guys have a discord for a more efficient way of discussing GRRLIB in general? Thanks again!

**Comment by Crayon2000** [comment]
As a programmer I hate to change the documentation to mention a limitation. So instead, I have decided to add the feature 😉

It should be available soon.

So this code:
```cpp
const int font_size = 70;
GRRLIB_PrintfTTF(5,   0, myFont, "This is my text", font_size, 0x00000000);
GRRLIB_PrintfTTF(5,  75, myFont, "This is my text", font_size, 0x00000010);
GRRLIB_PrintfTTF(5, 150, myFont, "This is my text", font_size, 0x00000040);
GRRLIB_PrintfTTF(5, 225, myFont, "This is my text", font_size, 0x00000080);
GRRLIB_PrintfTTF(5, 300, myFont, "This is my text", font_size, 0x000000C0);
GRRLIB_PrintfTTF(5, 375, myFont, "This is my text", font_size, 0x000000FF);
```

Will soon be able to generate this:
![image](https://github.com/GRRLIB/GRRLIB/assets/11451841/63e6656e-4dda-475b-9a4b-db22526378f3)

We are not on Discord, but you can use the GitHub Discussions page: https://github.com/GRRLIB/GRRLIB/discussions

**Comment by supertazon** [comment]
What?! You’re amazing! Thanks a lot! I’ll be on the lookout for the update and will go to the Discussion page for further questions/ideas

**Comment by Crayon2000** [comment]
Closing issue. PR #41 was merged into master.
