### ISSUE TITLE
$ cd C:\grr\GRRLIB bash: cd: C:grrGRRLIB: No such file or directory

### ISSUE THREAD

**Issue by Experiment9030** [GRRLIB/GRRLIB#42]
help pls

**Comment by Crayon2000** [comment]
I'm guessing you are trying to compile the lib on Windows. I'm guessing also that you have clone this repo in *C:\grr\GRRLIB*. I'm also guessing that your problem is that you cannot Change Directory (cd) into that folder.

... It seems mostly not like a GRRLIB problem.

**Comment by Experiment9030** [comment]
am i supposed to use msys2

**Comment by Crayon2000** [comment]
Have you installed DevkitPPC?

Did you read https://github.com/GRRLIB/GRRLIB#developing-for-the-wii?

**Comment by Experiment9030** [comment]
yes

**Comment by Crayon2000** [comment]
Are you able to compile the *template* source code from devkitpro?

**Comment by Experiment9030** [comment]
do you mean in C:\devkitPro\examples\wii\template

**Comment by Crayon2000** [comment]
yes

**Comment by Experiment9030** [comment]
ok

**Comment by Experiment9030** [comment]
never mind i figured it out
