### ISSUE TITLE
mkdir: illegal option -- -

### ISSUE THREAD

**Issue by LimeGradient** [GRRLIB/GRRLIB#48]
When trying to build GRRLIB, i get the error
```
libgrrlib.a
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory_name ...
make[2]: *** [install] Error 64
make[1]: *** [install] Error 1
make: *** [install] Error 1

```

**Comment by Crayon2000** [comment]
What command did you type to get this result?
Are you using the last tagged version or a specific branch?

**Comment by gofastlily** [comment]
I'm seeing this error when running `make install` as well, on both the `master` branch and the `v4.5.1` release.

I'm on macOS, so I'm becoming the root user before running `make PLATFORM=cube install`, as-per the discussion in this issue https://github.com/GRRLIB/GRRLIB/issues/36#issuecomment-1409329494.

Hope that's enough info to help out here.

**Comment by Crayon2000** [comment]
@gofastlily, I have updated the master branch, can you try again to check if it fixed the problem?

**Comment by gofastlily** [comment]
That fixed it, thank you so much!
