### ISSUE TITLE
ld cannot find [-lfreetype, -lbz2, -lpng, -ljpeg, -lz]: : No such file or directory

### ISSUE THREAD

**Issue by RedFireMRT84** [GRRLIB/GRRLIB#51]
Hi. I'm currently trying to use images and fonts to develop something for the Wii. I did the "make" command and I get this instead of finishing off the compiling process:
First it was this:

```
C:\GRRLIB-4.4.1\examples\be_gui>make
frnpd.ttf
recovery_instruction.mp3
BE.c
C:/GRRLIB-4.4.1/examples/be_gui/source/BE.c:1:10: fatal error: grrlib.h: No such file or directory
    1 | #include <grrlib.h>
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:21: BE.o] Error 1
make: *** [Makefile:105: build] Error 2
```

then this:

```
C:\GRRLIB-4.4.1\examples\be_gui>make
BE.c
In file included from C:/GRRLIB-4.4.1/examples/be_gui/source/BE.c:13:
C:/GRRLIB-4.4.1/examples/be_gui/source/all_gfx.h:22:10: fatal error: frnpd.h: No such file or directory
   22 | #include "frnpd.h"
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:21: BE.o] Error 1
make: *** [Makefile:105: build] Error 2
```

i putted the grrlib.h and the frnpd [my font] in the C:\devkitPro\libogc\include directory, now i get this:

```
linking ... be_gui.elf
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/devkitPro/libogc/lib/wii\libgrrlib.a(GRRLIB_core.o):C:/GRRLIB/GRRLIB/grrlib.h:176: multiple definition of `rmode'; BE.o:C:/projects/nintendo/wii/be_gui/source/BE.c:14: first defined here
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.2.0/../../../../powerpc-eabi/bin/ld.exe: C:/devkitPro/libogc/lib/wii\libgrrlib.a(GRRLIB_core.o):C:/GRRLIB/GRRLIB/grrlib.h:177: multiple definition of `xfb'; BE.o:C:/projects/nintendo/wii/be_gui/source/BE.c:15: first defined here
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.2.0/../../../../powerpc-eabi/bin/ld.exe: cannot find -lfreetype: No such file or directory
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.2.0/../../../../powerpc-eabi/bin/ld.exe: cannot find -lbz2: No such file or directory
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.2.0/../../../../powerpc-eabi/bin/ld.exe: cannot find -lpng: No such file or directory
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.2.0/../../../../powerpc-eabi/bin/ld.exe: cannot find -ljpeg: No such file or directory
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.2.0/../../../../powerpc-eabi/bin/ld.exe: cannot find -lz: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitPPC/wii_rules:31: /c/projects/nintendo/wii/be_gui/be_gui.elf] Error 1
make: *** [Makefile:105: build] Error 2
```

Some questions you might start asking that I might know and that I can answer are:
1. Did you install the required libraries? Well yes, I even tried uninstalling and reinstalling the libraries, but that doesn't count.

Now its my turn to ask y'all a question. Why I'm getting this compile error and is there a solution to this?

**Comment by Crayon2000** [comment]
To test that grrlib is installed properly, can you try to build any examples from the examples folder.

Did you installed all the dependencies with: `pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo`

**Comment by RedFireMRT84** [comment]
> To test that grrlib is installed properly, can you try to build any examples from the examples folder.
> 
> Did you installed all the dependencies with: `pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo`

i actually did build yalls examples and it pretty much worked, but for some reason mines doesnt.

and for this command:
`pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo`
yes, multiple times and i even tried uninstalling and reinstalling.

**Comment by Crayon2000** [comment]
Did you base your project Makefile on the template Makefile provided in the examples folder?

**Comment by RedFireMRT84** [comment]
I got it fixed

**Comment by Crayon2000** [comment]
Don't forget the latest GRRLIB version is [4.5.1](https://github.com/GRRLIB/GRRLIB/releases/tag/v4.5.1)

**Comment by RedFireMRT84** [comment]
Also for some reason if i were to have a image such as a png to be in my program, but the kbs are 300. The image would not load or display for some reason, but only in very small kbs it would.

**Comment by Crayon2000** [comment]
1. The width and height of the png file must be a multiple of 4
2. The size must be less than 1024px
3. Only 24bit and 32bit PNGs are allowed

**Comment by Crayon2000** [comment]
I'm closing this issue. If you have any question, go to [discussion page](https://github.com/GRRLIB/GRRLIB/discussions)
