### ISSUE TITLE
compiling on mac

### ISSUE THREAD

**Issue by guinea7pig** [GRRLIB/GRRLIB#58]
im trying to compile grrlib on mac os 14.4.1 (23E224) on arm64 
![Screenshot 2024-11-01 at 10 13 35 AM](https://github.com/user-attachments/assets/1d6af78a-a776-418f-adfa-5fe3a1747822)
it looks like  it installed but my project my project still gives a error about grrlib being missing i also dont know if his is how it should be installed best regard guinea7pig

**Comment by guinea7pig** [comment]
it also very presisntant on not being able to copy to portlibs

**Comment by guinea7pig** [comment]
![Screenshot 2024-11-08 at 10 12 32 AM](https://github.com/user-attachments/assets/273da9d1-2461-45d3-86f2-1e65be4bbae4)
 having another problem. im trying to compile pngu. i have all the libarys installed form 
-lgrrlib -lpngu `$(PREFIX)pkg-config freetype2 libpng libjpeg --libs` -lfat
the other stuff might be somthing that devkitpro related and not grrlib

**Comment by Crayon2000** [comment]
Follow the instructions on https://github.com/GRRLIB/GRRLIB?tab=readme-ov-file#installing-grrlib

> First, you need to make sure that all required library dependencies are installed.
> Install them with a single command:
> 
> ```bash
>   pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo
> ```

**Comment by Crayon2000** [comment]
On your mac you might need to use `dkp-pacman` instead of `pacman`

**Comment by Crayon2000** [comment]
I'm closing this "issue". If you need help, you may go to the [discussions page](https://github.com/GRRLIB/GRRLIB/discussions).
