### ISSUE TITLE
problems with pointers 

### ISSUE THREAD

**Issue by guinea7pig** [GRRLIB/GRRLIB#59]
i keep getting error with pointers like this
![Screenshot 2024-12-03 at 7 39 55 AM](https://github.com/user-attachments/assets/932e8fd5-29d0-4e04-abdc-9aed71b2e970)
this i how i do them
![Screenshot 2024-12-03 at 7 40 27 AM](https://github.com/user-attachments/assets/a391ddfd-a83d-41b0-aba3-35e99cb88b3e)
is this the correct way

**Comment by Crayon2000** [comment]
`GRRLIB_LoadTexture` loads a texture (or data with image content if you prefer): https://grrlib.github.io/GRRLIB/group___all_func.html#ga3bcf05b86d1d2345eef642fd6eb9912d

On your code code you are loading a char array (or a string if you prefer). Try to use `GRRLIB_texImg *tex_BMfont3_png = GRRLIB_LoadTexture(BMfont3_png);` with no quotes if your texture was generated *raw2c* and included like this : `#include "BMfont3_png.h"`
