### ISSUE TITLE
Compilation on Ubuntu WSL

### ISSUE THREAD

**Issue by sonich2401** [GRRLIB/GRRLIB#8]
I have been making WII stuff without any graphics. Just looking at the registers in Dolphin was good enogh for me but now I want to make actual games. I have been using Ubuntu WSL to compile my code because it is more reliable than msys2 in my opinion. When I tried to install GRRLIB it gave me manny errors. I worked through a few but now I cannot figure it out. I tried running msys2 and it compiled but it is annoying to have to use msys2 rather than WSL which works with VSCode. I get one of two errors 
```make
make[1]: Entering directory '/mnt/c/grr/GRRLIB/GRRLIB'
GRRLIB_gecko.c
powerpc-eabi-gcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
make[1]: *** [/mnt/c/devkitPro/devkitPPC/base_rules:24: GRRLIB_gecko.o] Error 1
make[1]: Leaving directory '/mnt/c/grr/GRRLIB/GRRLIB'
make: *** [Makefile:4: all] Error 1
```
or sometimes i get this
```make
liblto_plugin-0.dll not found
```
I don't really know why it is an issue that i am on WSL rather than msys2 and the only changes that I have made to the original make file is using absoulte path names rather than makefile varibles that had nothing in them. If I did not do this it would fail because it couldnt find powerpc-eabi-gcc.exe

Is it possible that after compiling GRRLIB with msys2 that i could move it to Ubuntu?

**Comment by Crayon2000** [comment]
Hello, from what I see. It does not seems like you are using WSL. Because WSL will use Linux binaries and here I see an exe (_powerpc-eabi-gcc.exe_) and dll (_liblto_plugin-0.dll_) file.

Are you sure Devkitpro is installed? It should be in _/opt/devkitpro_
You can test with `/opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc --version`

**Comment by sonich2401** [comment]
> Hello, from what I see. It does not seems like you are using WSL. Because WSL will use Linux binaries and here I see an exe (_powerpc-eabi-gcc.exe_) and dll (_liblto_plugin-0.dll_) file.
> 
> Are you sure Devkitpro is installed? It should be in _/opt/devkitpro_
> You can test with `/opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc --version`


`/opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc --version
powerpc-eabi-gcc (devkitPPC release 38) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

Its installed

**Comment by sonich2401** [comment]
Ive been able to compile other things for the wii so idk why it matters if its an exe or not. msys2 was able to compile it just fine when it was an exe

**Comment by Crayon2000** [comment]
Try the following and give me the result:
```bash
echo $DEVKITPRO
```

**Comment by sonich2401** [comment]
> Try the following and give me the result:
> 
> ```shell
> echo $DEVKITPRO
> ```
Result:
/opt/devkitpro

**Comment by Crayon2000** [comment]
I have no idea! Do a `make clean` in the GRRLIB folder.

**Comment by sonich2401** [comment]
> I have no idea! Do a `make clean` in the GRRLIB folder.

Figrued it out. For some reason inside of the makefile $DEVKITPRO is "/opt/devkitPro" which was fine for msys2 because it figured out that i really wanted to go to /opt/devkitpro whereas Ubuntu was very literal and couln't resolve "/opt/devkitPro"
